create table public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  subject text not null check (char_length(btrim(subject)) between 4 and 140),
  category text not null default 'duvida' check (category in ('duvida', 'problema', 'financeiro', 'sugestao', 'outro')),
  priority text not null default 'normal' check (priority in ('baixa', 'normal', 'alta', 'urgente')),
  status text not null default 'aberto' check (status in ('aberto', 'em_atendimento', 'aguardando_cliente', 'resolvido', 'fechado')),
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  author_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  message text not null check (char_length(btrim(message)) between 1 and 5000),
  is_staff boolean not null default false,
  created_at timestamptz not null default now()
);

create index support_tickets_user_id_idx on public.support_tickets (user_id);
create index support_tickets_status_idx on public.support_tickets (status, last_message_at desc);
create index support_ticket_messages_ticket_id_idx on public.support_ticket_messages (ticket_id, created_at);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

create policy "Usuarios visualizam seus tickets"
on public.support_tickets for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Administradores visualizam todos os tickets"
on public.support_tickets for select to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = (select auth.uid()) and profiles.role = 'admin'
));

create policy "Usuarios criam seus tickets"
on public.support_tickets for insert to authenticated
with check ((select auth.uid()) = user_id and status = 'aberto');

create policy "Administradores atualizam tickets"
on public.support_tickets for update to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = (select auth.uid()) and profiles.role = 'admin'
))
with check (exists (
  select 1 from public.profiles
  where profiles.id = (select auth.uid()) and profiles.role = 'admin'
));

create policy "Participantes visualizam mensagens"
on public.support_ticket_messages for select to authenticated
using (exists (
  select 1 from public.support_tickets
  where support_tickets.id = support_ticket_messages.ticket_id
));

create policy "Participantes enviam mensagens"
on public.support_ticket_messages for insert to authenticated
with check (
  (select auth.uid()) = author_id
  and exists (
    select 1 from public.support_tickets
    where support_tickets.id = support_ticket_messages.ticket_id
  )
  and is_staff = exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.role = 'admin'
  )
);

grant select, insert on public.support_tickets to authenticated;
grant update (status, priority, updated_at) on public.support_tickets to authenticated;
grant select, insert on public.support_ticket_messages to authenticated;
grant usage, select on sequence public.support_tickets_id_seq to authenticated;

create schema if not exists private;

create or replace function private.touch_support_ticket()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.support_tickets
  set last_message_at = new.created_at,
      updated_at = new.created_at,
      status = case
        when new.is_staff then 'aguardando_cliente'
        when status in ('resolvido', 'fechado', 'aguardando_cliente') then 'aberto'
        else status
      end
  where id = new.ticket_id;
  return new;
end;
$$;

revoke all on function private.touch_support_ticket() from public, anon, authenticated;

create trigger support_message_touch_ticket
after insert on public.support_ticket_messages
for each row execute function private.touch_support_ticket();
