import type { CatalogItem } from './types';

export const CATALOG: { name: string; items: { name: string; tablePrice: number; minPrice: number }[] }[] = [
  { name: 'Prótese/Implante', items: [
    { name: 'Prótese total ou PPR com grampo (1 unidade) - Alemão', tablePrice: 3500, minPrice: 3000 },
    { name: 'Prótese total ou PPR com grampo (1 unidade) - Italiano (mais popular)', tablePrice: 3000, minPrice: 2500 },
    { name: 'Prótese total ou PPR com grampo ou Flex (1 unidade) - Simples', tablePrice: 2700, minPrice: 2300 },
    { name: 'Prótese total ou PPR com grampo ou Flex (par) - Alemão', tablePrice: 5500, minPrice: 4900 },
    { name: 'Prótese total ou PPR com grampo ou Flex (par) - Italiano (mais popular)', tablePrice: 5000, minPrice: 4500 },
    { name: 'Prótese total ou PPR com grampo ou Flex (par) - Simples', tablePrice: 4700, minPrice: 4300 },
    { name: 'Coroa de porcelana (1 unidade) - Zircônia', tablePrice: 3200, minPrice: 2800 },
    { name: 'Coroa de porcelana (1 unidade) - Pura', tablePrice: 2700, minPrice: 2200 },
    { name: 'Coroa de porcelana (1 unidade) - Metalocerâmica', tablePrice: 2200, minPrice: 1900 },
    { name: 'Coroa (1 unidade) - Resina', tablePrice: 1200, minPrice: 1200 },
    { name: 'Adesiva de resina', tablePrice: 2000, minPrice: 1500 },
    { name: 'Pino de fibra de vidro - Molares e Pré-molares', tablePrice: 1200, minPrice: 800 },
    { name: 'Pino de fibra de vidro - Incisivos', tablePrice: 800, minPrice: 500 },
    { name: 'Implante unitário', tablePrice: 3300, minPrice: 2800 },
    { name: 'Enxerto', tablePrice: 4000, minPrice: 1000 },
    { name: 'Placa de bruxismo', tablePrice: 1800, minPrice: 1500 },
    { name: 'Facetas/Lentes de contato porcelana - 1 elemento', tablePrice: 2200, minPrice: 2200 },
    { name: 'Provisório PPA', tablePrice: 1000, minPrice: 800 },
    { name: 'Provisório unitário (adesiva provisória)', tablePrice: 500, minPrice: 400 },
    { name: 'Onlay (Porcelana pura)', tablePrice: 2400, minPrice: 2000 },
    { name: 'Onlay (Resina LAB)', tablePrice: 1200, minPrice: 950 },
  ]},
  { name: 'Protocolo', items: [
    { name: 'Protocolo superior tranquilo', tablePrice: 15000, minPrice: 14000 },
    { name: 'Protocolo superior carga imediata', tablePrice: 18000, minPrice: 17000 },
    { name: 'Protocolo superior buxa com enxerto max', tablePrice: 25000, minPrice: 25000 },
    { name: 'Protocolo superior buxa com enxerto médio', tablePrice: 18000, minPrice: 18000 },
    { name: 'Protocolo superior buxa com enxerto min', tablePrice: 16500, minPrice: 16500 },
    { name: 'Protocolo inferior tranquilo', tablePrice: 15000, minPrice: 13000 },
    { name: 'Protocolo inferior carga', tablePrice: 15000, minPrice: 15000 },
    { name: 'Overdenture - Maxila', tablePrice: 7000, minPrice: 5500 },
    { name: 'Overdenture - Mandíbula', tablePrice: 6000, minPrice: 5000 },
    { name: 'Limpeza Protocolo', tablePrice: 500, minPrice: 400 },
    { name: 'Limpeza de prótese total/over/PPR - 1 unidade', tablePrice: 300, minPrice: 300 },
    { name: 'Limpeza de prótese total/over/PPR - 2 unidades', tablePrice: 400, minPrice: 400 },
    { name: 'Protocolo somente parte protética', tablePrice: 7500, minPrice: 6000 },
  ]},
  { name: 'Ortodontia', items: [
    { name: 'Mensalidade ortodôntica', tablePrice: 140, minPrice: 79.90 },
    { name: 'Mensalidade autoligado', tablePrice: 190, minPrice: 135 },
    { name: 'Compra do autoligado', tablePrice: 2000, minPrice: 1500 },
    { name: 'Aparelho ortopédico', tablePrice: 1500, minPrice: 1250 },
    { name: 'Contenção superior e inferior após tratamento', tablePrice: 450, minPrice: 450 },
  ]},
  { name: 'Clínico geral', items: [
    { name: 'Raspagem sub', tablePrice: 450, minPrice: 450 },
    { name: 'Raspagem simples', tablePrice: 350, minPrice: 350 },
    { name: 'Restauração', tablePrice: 240, minPrice: 50 },
    { name: 'Frenectomia', tablePrice: 800, minPrice: 450 },
    { name: 'Extração simples', tablePrice: 150, minPrice: 50 },
    { name: 'Extração média', tablePrice: 200, minPrice: 50 },
    { name: '3º molar - Inferior simples', tablePrice: 500, minPrice: 400 },
    { name: '3º molar - Inferior complexo', tablePrice: 800, minPrice: 600 },
    { name: '3º molar - Superior', tablePrice: 450, minPrice: 300 },
    { name: '3º molar - Superior muito simples', tablePrice: 300, minPrice: 300 },
    { name: 'Canal molar', tablePrice: 900, minPrice: 400 },
    { name: 'Canal pré-molar', tablePrice: 600, minPrice: 400 },
    { name: 'Canal incisivo', tablePrice: 600, minPrice: 400 },
    { name: 'Retratamento de Molar', tablePrice: 1200, minPrice: 900 },
    { name: 'Retratamento de Pré-molar', tablePrice: 900, minPrice: 700 },
    { name: 'Retratamento de Incisivo', tablePrice: 800, minPrice: 600 },
    { name: 'Remoção espícula óssea', tablePrice: 350, minPrice: 270 },
  ]},
  { name: 'Estética', items: [
    { name: 'Resina estética anterior simples', tablePrice: 300, minPrice: 250 },
    { name: 'Resina estética anterior complexa', tablePrice: 400, minPrice: 300 },
    { name: 'Clareamento de consultório', tablePrice: 1500, minPrice: 1200 },
    { name: 'Clareamento caseiro', tablePrice: 900, minPrice: 600 },
    { name: 'Faceta', tablePrice: 800, minPrice: 600 },
    { name: 'Técnica Associada de Clareamento Consultório + Caseiro', tablePrice: 2400, minPrice: 1500 },
  ]},
  { name: 'Emergências', items: [
    { name: 'Coroa cimentação', tablePrice: 200, minPrice: 180 },
    { name: 'Dor (abertura)', tablePrice: 250, minPrice: 200 },
  ]},
  { name: 'Radiografias', items: [
    { name: 'Tomografia por arcada', tablePrice: 350, minPrice: 350 },
    { name: 'Documentação ortodôntica', tablePrice: 180, minPrice: 180 },
  ]},
];

export const FLAT_CATALOG: CatalogItem[] = CATALOG.flatMap(category =>
  category.items.map(item => ({
    category: category.name,
    name: item.name,
    tablePrice: item.tablePrice,
    minPrice: item.minPrice ?? item.tablePrice,
  }))
);
